{"uuid": "3991da27-6f04-4842-b485-83385ac27cee", "children": ["fd5ae8cd-459a-4ffd-84d5-4e4b87efc49d"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=121.0.6167.184)\nStacktrace:\n0   chromedriver                        0x0000000105062814 chromedriver + 4040724\n1   chromedriver                        0x000000010505aa18 chromedriver + 4008472\n2   chromedriver                        0x0000000104ccd870 chromedriver + 284784\n3   chromedriver                        0x0000000104ca8064 chromedriver + 131172\n4   chromedriver                        0x0000000104d372b0 chromedriver + 717488\n5   chromedriver                        0x0000000104d4a75c chromedriver + 796508\n6   chromedriver                        0x0000000104d0574c chromedriver + 513868\n7   chromedriver                        0x0000000104d06044 chromedriver + 516164\n8   chromedriver                        0x0000000105027a3c chromedriver + 3799612\n9   chromedriver                        0x000000010502bf1c chromedriver + 3817244\n10  chromedriver                        0x0000000105010298 chromedriver + 3703448\n11  chromedriver                        0x000000010502ca64 chromedriver + 3820132\n12  chromedriver                        0x0000000105003054 chromedriver + 3649620\n13  chromedriver                        0x0000000105049e74 chromedriver + 3939956\n14  chromedriver                        0x0000000105049fec chromedriver + 3940332\n15  chromedriver                        0x000000010505a698 chromedriver + 4007576\n16  libsystem_pthread.dylib             0x000000018336a034 _pthread_start + 136\n17  libsystem_pthread.dylib             0x0000000183364e3c thread_start + 8\n\n", "trace": "  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Ganesh/PyWebAutomation/tests/vmoLoginTests/test_loginvmo.py\", line 13, in setup\n    driver.maximize_window()\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 499, in maximize_window\n    self.execute(command, None)\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1708168725336, "stop": 1708168729216}], "start": 1708168725336, "stop": 1708168729268}